# Site settings
author: LaNice Powell 
title: My Journey to Graduate from Flatiron Schools Bootcamp 
header-img: img/home-bg.png
email: lanicemp@aol.com
copyright_name: LaNice Powell 
description: > # this means to ignore newlines until "baseurl:"
  Life of an online student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: beautifullais
github_username:  lanicemp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
